# Generated by Django 4.0.3 on 2022-03-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_r', models.IntegerField()),
                ('F_I_SH', models.CharField(max_length=255)),
                ('Guruh', models.CharField(max_length=255)),
                ('Ona_tili', models.IntegerField()),
                ('Matem', models.IntegerField()),
                ('Tarix', models.IntegerField()),
                ('blok_1', models.IntegerField()),
                ('blok_2', models.IntegerField()),
                ('Jami', models.FloatField()),
            ],
        ),
    ]
