# Generated by Django 4.0.3 on 2022-03-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probalar_app', '0013_alter_sentyabr_1_matem_alter_sentyabr_1_ona_tili_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aprel_1',
        ),
        migrations.DeleteModel(
            name='Dekabr_1',
        ),
        migrations.DeleteModel(
            name='Fevral_1',
        ),
        migrations.DeleteModel(
            name='Mart_1',
        ),
        migrations.DeleteModel(
            name='May_1',
        ),
        migrations.DeleteModel(
            name='Noyabr_1',
        ),
        migrations.DeleteModel(
            name='Oktyabr_1',
        ),
        migrations.DeleteModel(
            name='Yanvar_1',
        ),
        migrations.AlterField(
            model_name='sentyabr_1',
            name='Jami',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
