# Generated by Django 4.0.3 on 2022-03-24 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probalar_app', '0014_delete_aprel_1_delete_dekabr_1_delete_fevral_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oktyabr_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_I_SH', models.CharField(max_length=255, null=True)),
                ('Guruh', models.CharField(max_length=255, null=True)),
                ('Ona_tili', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('Matem', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('Tarix', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('blok_1', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('blok_2', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('Jami', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'verbose_name': '1 -kurslar Oktyabr_1',
                'verbose_name_plural': '1 -kurslar Oktyabr_1',
                'ordering': ['-Jami'],
            },
        ),
    ]
