# Generated by Django 4.0.3 on 2022-03-25 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probalar_app', '0016_aprel_1_aprel_2_dekabr_1_dekabr_2_fevral_1_fevral_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aprel_1',
            options={'ordering': ['-Jami'], 'verbose_name': '1 -kurslar Aprel', 'verbose_name_plural': '1 -kurslar Aprel'},
        ),
        migrations.AlterModelOptions(
            name='aprel_2',
            options={'ordering': ['-Jami'], 'verbose_name': '2 -kurslar Aprel', 'verbose_name_plural': '2 -kurslar Aprel'},
        ),
        migrations.AlterModelOptions(
            name='dekabr_1',
            options={'ordering': ['-Jami'], 'verbose_name': '1 -kurslar Dekabr', 'verbose_name_plural': '1 -kurslar Dekabr'},
        ),
        migrations.AlterModelOptions(
            name='dekabr_2',
            options={'ordering': ['-Jami'], 'verbose_name': '2 -kurslar Dekabr', 'verbose_name_plural': '2 -kurslar Dekabr'},
        ),
        migrations.AlterModelOptions(
            name='fevral_1',
            options={'ordering': ['-Jami'], 'verbose_name': '1 -kurslar Fevral', 'verbose_name_plural': '1 -kurslar Fevral'},
        ),
        migrations.AlterModelOptions(
            name='fevral_2',
            options={'ordering': ['-Jami'], 'verbose_name': '2 -kurslar Fevral', 'verbose_name_plural': '2 -kurslar Fevral'},
        ),
        migrations.AlterModelOptions(
            name='mart_1',
            options={'ordering': ['-Jami'], 'verbose_name': '1 -kurslar Mart', 'verbose_name_plural': '1 -kurslar Mart'},
        ),
        migrations.AlterModelOptions(
            name='mart_2',
            options={'ordering': ['-Jami'], 'verbose_name': '2 -kurslar Mart', 'verbose_name_plural': '2 -kurslar Mart'},
        ),
        migrations.AlterModelOptions(
            name='may_1',
            options={'ordering': ['-Jami'], 'verbose_name': '1 -kurslar May', 'verbose_name_plural': '1 -kurslar May'},
        ),
        migrations.AlterModelOptions(
            name='may_2',
            options={'ordering': ['-Jami'], 'verbose_name': '2 -kurslar May', 'verbose_name_plural': '2 -kurslar May'},
        ),
        migrations.AlterModelOptions(
            name='noyabr_1',
            options={'ordering': ['-Jami'], 'verbose_name': '1 -kurslar Noyabr', 'verbose_name_plural': '1 -kurslar Noyabr'},
        ),
        migrations.AlterModelOptions(
            name='noyabr_2',
            options={'ordering': ['-Jami'], 'verbose_name': '2 -kurslar Noyabr', 'verbose_name_plural': '2 -kurslar Noyabr'},
        ),
        migrations.AlterModelOptions(
            name='oktyabr_1',
            options={'ordering': ['-Jami'], 'verbose_name': '1 -kurslar Oktyabr', 'verbose_name_plural': '1 -kurslar Oktyabr'},
        ),
        migrations.AlterModelOptions(
            name='oktyabr_2',
            options={'ordering': ['-Jami'], 'verbose_name': '2 -kurslar Oktyabr', 'verbose_name_plural': '2 -kurslar Oktyabr'},
        ),
        migrations.AlterModelOptions(
            name='sentyabr_2',
            options={'ordering': ['-Jami'], 'verbose_name': '2 -kurslar Sentyabr', 'verbose_name_plural': '2 -kurslar Sentyabr'},
        ),
        migrations.AlterModelOptions(
            name='yanvar_1',
            options={'ordering': ['-Jami'], 'verbose_name': '1 -kurslar Yanvar', 'verbose_name_plural': '1 -kurslar Yanvar'},
        ),
        migrations.AlterModelOptions(
            name='yanvar_2',
            options={'ordering': ['-Jami'], 'verbose_name': '2 -kurslar Yanvar', 'verbose_name_plural': '2 -kurslar Yanvar'},
        ),
    ]
